spring.application.name=compliance-tracker

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5434/compliance_tracker
spring.datasource.username=postgres
spring.datasource.password=devpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true